# -*- coding: utf-8 -*-
"""ayatec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14q8GDQFGW4nRkVOpXO-AgqDOPG0Zba90
"""

import pandas as pd

train_df = pd.read_csv("QH-QA-25_Subtask2_ayatec_v1.3_train.tsv", sep="\t", names=["Question_ID", "Question"])
dev_df = pd.read_csv("QH-QA-25_Subtask2_ayatec_v1.3_dev.tsv", sep="\t", names=["Question_ID", "Question"])
test_df = pd.read_csv("QH-QA-25_Subtask2_ayatec_v1.3_test.tsv", sep="\t", names=["Question ID", "Question"])

train_df.info(), dev_df.info(), test_df.info()

train_df.head(), dev_df.head(), test_df.head()

qrels_train = pd.read_csv("QH-QA-25_Subtask2_ayatec_v1.3_qrels_train.gold", sep="\s+", header=None, usecols=[0, 2], names=["Question_ID", "Passage_ID"])
qrels_dev = pd.read_csv("QH-QA-25_Subtask2_ayatec_v1.3_qrels_dev.gold", sep="\s+", header=None, usecols=[0, 2], names=["Question_ID", "Passage_ID"])

qrels_train.info(), qrels_dev.info()

qrels_train.head(), qrels_dev.head()

def categorize(df):
    counts = df.groupby("Question_ID")["Passage_ID"].apply(list)
    zero_answer = []
    one_answer = []
    multi_answer = []

    for qid, pids in counts.items():
        if all(pid == "-1" for pid in pids):
            zero_answer.append(qid)
        elif len(set(pids) - {"-1"}) == 1:
            one_answer.append(qid)
        else:
            multi_answer.append(qid)

    return {
        "0-answer": len(zero_answer),
        "1-answer": len(one_answer),
        "more-than-1": len(multi_answer),
        "total_questions": len(counts)
    }

print("Train:", categorize(qrels_train))
print("Dev:", categorize(qrels_dev))